# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5.8

    - uses: actions/checkout@v3
    - name: Build Target 1
      run: swift build --target 
    - name: Run tests
      run: swift test -v
